services:
  bakery-backend:
    build:
      context: ./bakery-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - bakery-network

  bakery-frontend:
    build:
      context: ./bakery-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    networks:
      - bakery-network

networks:
  bakery-network:
    driver: bridge